name: Add a resource
description: Request to add a new resource to the AzNames module
title: "[ADD]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to make AzNames even more powerful!
  - type: input
    id: resourcename
    attributes:
      label: Resource Name
      description: What is the name of the resource you would like to add?
      placeholder: ex. App Service
    validations:
      required: true
  - type: input
    id: minlenght
    attributes:
      label: Minimum lenght
      description: What is the minimum lenght for the resource name (number only)?
      placeholder: 2
    validations:
      required: true
  - type: input
    id: maxlenght
    attributes:
      label: Maximum lenght
      description: What is the maximum lenght for the resource name (number only)?
      placeholder: 10
    validations:
      required: true
  - type: dropdown
    id: scope
    attributes:
      label: Resource Name Scope
      description: What is the scope for the resource name?
      options:
        - Global
        - Subscription
        - Resource Group
    validations:
      required: true
  - type: dropdown
    id: regex
    attributes:
      label: Resource Name Rule
      description: Resource Name Rule schema (in regex)
      options:
        - "^(?=.{MIN,MAX}$)[a-z0-9][a-zA-Z0-9-]+[a-z0-9]"
        - "^(?=.{MIN,MAX}$)[a-z0-9]+$"
        - Custom
    validations:
      required: true
  - type: checkboxes
    id: dashes
    attributes:
      label: The resource name accepts dashes
      description: Check if the resource name accepts dashes
      options:
        - label: Dashes allowed
          required: true
  - type: input
    id: resourceurl
    attributes:
      label: Microsoft docs URL
      description: Can you share the link of the Microsoft official documentation?
      placeholder: https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules#microsoftweb
    validations:
      required: true